FROM nginx


# RUN cp /etc/nginx/conf.d/defualt.conf /tmp/backup.conf


# RUN rm /etc/nginx/conf.d/defualt.conf

COPY nginx.conf /etc/nginx/conf.d
# CMD ["/usr/local/sbin/nginx", "-c", "/etc/nginx/nginx.conf"]

